/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Profile = IDL.Record({
  'id' : IDL.Principal,
  'bio' : IDL.Text,
  'displayName' : IDL.Text,
  'joinDate' : IDL.Int,
  'interests' : IDL.Vec(IDL.Text),
});
export const Reply = IDL.Record({
  'content' : IDL.Text,
  'author' : IDL.Principal,
  'timestamp' : IDL.Int,
});
export const Post = IDL.Record({
  'id' : IDL.Nat,
  'content' : IDL.Text,
  'author' : IDL.Principal,
  'timestamp' : IDL.Int,
  'replies' : IDL.Vec(Reply),
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addReply' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createPost' : IDL.Func([IDL.Text], [], []),
  'createProfile' : IDL.Func([IDL.Text, IDL.Text, IDL.Vec(IDL.Text)], [], []),
  'findProfilesByInterests' : IDL.Func(
      [IDL.Vec(IDL.Text)],
      [IDL.Vec(Profile)],
      ['query'],
    ),
  'getAllPosts' : IDL.Func([], [IDL.Vec(Post)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(Profile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getProfile' : IDL.Func([IDL.Principal], [IDL.Opt(Profile)], ['query']),
  'getUserProfile' : IDL.Func([IDL.Principal], [IDL.Opt(Profile)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Vec(IDL.Text)],
      [],
      [],
    ),
  'updateProfile' : IDL.Func([IDL.Text, IDL.Text, IDL.Vec(IDL.Text)], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Profile = IDL.Record({
    'id' : IDL.Principal,
    'bio' : IDL.Text,
    'displayName' : IDL.Text,
    'joinDate' : IDL.Int,
    'interests' : IDL.Vec(IDL.Text),
  });
  const Reply = IDL.Record({
    'content' : IDL.Text,
    'author' : IDL.Principal,
    'timestamp' : IDL.Int,
  });
  const Post = IDL.Record({
    'id' : IDL.Nat,
    'content' : IDL.Text,
    'author' : IDL.Principal,
    'timestamp' : IDL.Int,
    'replies' : IDL.Vec(Reply),
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addReply' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createPost' : IDL.Func([IDL.Text], [], []),
    'createProfile' : IDL.Func([IDL.Text, IDL.Text, IDL.Vec(IDL.Text)], [], []),
    'findProfilesByInterests' : IDL.Func(
        [IDL.Vec(IDL.Text)],
        [IDL.Vec(Profile)],
        ['query'],
      ),
    'getAllPosts' : IDL.Func([], [IDL.Vec(Post)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(Profile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getProfile' : IDL.Func([IDL.Principal], [IDL.Opt(Profile)], ['query']),
    'getUserProfile' : IDL.Func([IDL.Principal], [IDL.Opt(Profile)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Vec(IDL.Text)],
        [],
        [],
      ),
    'updateProfile' : IDL.Func([IDL.Text, IDL.Text, IDL.Vec(IDL.Text)], [], []),
  });
};

export const init = ({ IDL }) => { return []; };